### ISSUE TITLE
UnauthorizedOperation flashing Plug

### ISSUE THREAD

**Issue by woody2010** [elahd/esp2ino#18]
I tried updating the plug to version .80 and got the same result. Any ideas?

Device type:      Plug (WLPP1)
Device name:      Pump
Firmware version: 1.2.0.59
IP Address:       192.168.4.87

Pushing firmware to this device? [y/N]:y
INFO:root:Pushing firmware URL to device.
Traceback (most recent call last):
  File "wyze_updater.py", line 401, in <module>
  File "wyze_updater.py", line 286, in update_devices
  File "wyze_updater.py", line 164, in push_update
  File "wyze_updater.py", line 158, in run_action
  File "wyze_updater.py", line 141, in device_api
RuntimeError: Request failed, error 3005:UnauthorizedOperation
[16990] Failed to execute script wyze_updater

**Comment by woody2010** [comment]
Now I see that my issue is the same as the other persons.
